"""Course-specific exercises, checks and reference solutions in both languages."""
EXERCISES = {
 "01-fasta-to-protein":{
  "en":("Explain why `[50:494]` is correct for CDS 51..494, and what changes if the start index is 51.",
    "Change WINDOW from 80 to 40. Keep the same transcript data and label the new window size.",
    "The correct CDS has 444 bases. Starting at index 51 removes one base: the 443-base length fails the complete-CDS check. A smaller window shows more local variation; it cannot establish a regulatory mechanism.",
    "Add an ambiguous-base count beside each GC fraction using only the standard library and the current packages. Keep the A/C/G/T denominator explicit.",
    "Add a reverse-complement function for IUPAC DNA symbols and a double-reverse-complement assertion. Explain why reverse-complementing an annotated forward CDS is not a replacement for strand annotation.",
    "Check that the original two RefSeq translations still match; test N-only GC as NaN, invalid symbols as an error, and reverse complement twice as identity."),
  "zh-hans":("解释为什么 CDS 51..494 应使用 `[50:494]`，并预测把起始索引改成 51 会怎样。",
    "将 WINDOW 从 80 改为 40，保持原始转录本不变，更新图中的窗口说明。",
    "正确 CDS 为 444 个碱基。使用起始索引 51 会删去一个碱基，长度变成 443，无法通过完整 CDS 校验。较小窗口展示更多局部变化，不能据此证明调控机制。",
    "只使用标准库及当前包，在每个 GC 值旁添加模糊碱基计数，明确保留 A/C/G/T 分母。",
    "添加支持 IUPAC DNA 符号的反向互补函数，并断言执行两次后恢复原序列。解释为何对注释中的正向 CDS 做反向互补不能代替链方向注释。",
    "检查两份 RefSeq 翻译仍完全一致；N-only GC 应为 NaN，非法符号应报错，两次反向互补应恢复原序列。")},
 "02-affine-sequence-alignment":{
  "en":("Calculate the penalty of a one-base and four-base gap with the default scoring.",
    "Rerun with gap-open −5, keeping every other parameter fixed. Compare scores and gap characters.",
    "The penalties are −3 and −6. A changed score can alter the chosen path. It does not mean the input sequences have changed. Removing global gaps must still recover each complete CDS.",
    "Add an independent function that rescales an existing alignment by iterating over matches, mismatches and consecutive gap runs; compare its score to the dynamic-programming result.",
    "Plot global identity and coverage for three mismatch penalties. Use the existing affine implementation and keep all-column versus nongap identity distinct.",
    "Use synthetic short strings only as tests: identical sequences, a four-base deletion and a local shared segment. Validate score, recovered global strings and local source intervals."),
  "zh-hans":("用默认评分计算长度 1 和长度 4 的缺口罚分。",
    "仅把 gap-open 改为 −5，重新运行，比较得分及缺口字符数。",
    "罚分分别为 −3 和 −6。修改评分可能改变最优路径，但不会改变输入序列。全局比对去除缺口后仍应恢复完整 CDS。",
    "添加独立函数，逐列统计一致、替换及连续缺口段，重新计算已有比对得分，并与动态规划结果比较。",
    "对三个 mismatch 参数绘制全局一致性及覆盖率，使用已有仿射实现，并区分全部列与非缺口列的分母。",
    "仅在测试中使用短合成序列，覆盖完全一致、长度 4 的缺失与局部共享片段；验证得分、原序列恢复及局部坐标。")},
 "03-airway-expression":{
  "en":("Why should each donor have exactly one control and one treated sample?", "Compare PCA colors by donor instead of condition. Keep the same matrix and coordinates.",
    "Pairing removes a donor's baseline from the descriptive difference. Relabeling colors does not alter PCA coordinates. A condition-only analysis can confound donor differences with treatment.",
    "Add a PCA legend that separately encodes donor with marker shape and condition with color, using only NumPy, Pandas and Matplotlib. Keep the exact input matrix and explain variance unchanged.",
    "Add a filter-sensitivity table for minimum counts 5, 10 and 20, retaining the four-sample requirement. Recalculate size factors each time and report candidate counts without assigning DEG p-values.",
    "Verify eight correctly ordered samples, four complete pairs, positive factors, unchanged source library totals and finite transformed values. Reordered metadata must raise an error."),
  "zh-hans":("为什么每个供体必须恰好有一个对照和一个处理样本？", "将 PCA 颜色改为供体，保持输入矩阵和坐标不变。",
    "配对差值去除了该供体的表达基线。修改配色不应改变 PCA 坐标。只考虑处理条件的分析可能混入供体差异。",
    "只使用 NumPy、Pandas 和 Matplotlib，为 PCA 分别用形状编码供体、颜色编码条件，保持输入矩阵与解释方差不变。",
    "添加最低 counts 为 5、10、20 的过滤敏感性表，保留至少 4 个样本的要求；每次重算 size factors 并报告候选数，不赋予 DEG p 值。",
    "验证样本顺序、4 个完整配对、正数 factors、原始文库总和与有限的变换值；打乱注释顺序必须报错。")},
 "04-reactome-enrichment":{
  "en":("What are N, K, n and k for the first result row? Why is every tested pathway included in BH?", "Set min_effect to 2 and repeat the full test family, including zero-overlap terms.",
    "N is the annotated measured background, K the term size within it, n the mapped directional candidate count and k the overlap. Correcting only interesting terms understates multiplicity. Stronger screening changes the question as well as the candidate set.",
    "Add the N/K/n/k values to the displayed table and validate one hypergeometric tail by summing the probability mass function. Preserve the measured background and both-direction BH family.",
    "Add a sensitivity comparison using all measured annotated genes versus expression-filtered annotated genes. Label the former as a different universe and explain why its p-values answer a different question.",
    "Check every candidate belongs to the chosen universe, zero overlap gives p=1, empty candidate sets give p=q=1, q stays in [0,1], and all eligible tests remain in the export."),
  "zh-hans":("第一行结果中的 N、K、n、k 各表示什么？为什么 BH 应包含所有检验通路？", "将 min_effect 改为 2，重新运行完整检验族，保留零重叠通路。",
    "N 是有注释的实测背景，K 是该背景内通路大小，n 是该方向已映射候选数，k 是重叠数。只校正有趣的通路会低估多重检验。更严格筛选改变的不只是候选数，也改变研究问题。",
    "在显示表中添加 N/K/n/k，用概率质量函数求和独立核验一个超几何尾概率，保持实测背景与双方向 BH 检验族。",
    "比较所有实测且有注释基因与通过表达过滤且有注释基因作为背景的敏感性；明确说明它们是不同背景，p 值回答不同问题。",
    "检查候选均属于背景；零重叠 p=1；空候选 p=q=1；q 位于 [0,1]；所有合格检验保留在导出表。")},
 "05-string-physical-network":{
  "en":("Why must an isolated query protein remain visible?", "Change THRESHOLD from 0.7 to 0.95 and compare the isolates with the sensitivity table.",
    "Dropping isolates changes the node universe and hides lack of evidence within the query. Increasing the threshold can remove edges but cannot add them when the snapshot and nodes are fixed.",
    "Create a side-by-side network view for confidence thresholds 0.7 and 0.95 with one shared seeded layout. Keep all 12 nodes and show their STRING identifiers in a table.",
    "Add a separate evidence audit listing edges with experimental score ≥0.7. Explain that this is an additional evidence filter within the frozen physical network.",
    "Check 12 nodes at every threshold, no self-loops, no added neighbors, correct human species, and a monotonically nonincreasing edge count as the threshold rises."),
  "zh-hans":("为什么孤立查询蛋白仍应显示在图中？", "将 THRESHOLD 从 0.7 改为 0.95，与敏感性表中的孤立节点数比较。",
    "删除孤立节点会改变节点背景，掩盖查询范围内的证据缺口。快照及节点固定时，升高阈值可以删除边，但不能增加边。",
    "用一个共享的固定随机布局，并排展示 0.7 与 0.95 的网络，保留全部 12 个节点，表格中显示 STRING 标识符。",
    "添加实验证据得分 ≥0.7 的边列表，明确这是冻结物理网络内部的额外证据过滤。",
    "检查各阈值均有 12 个节点、没有自环或额外邻居、物种为人类，且随阈值升高边数不增加。")},
 "06-hemoglobin-structure":{
  "en":("Why can SEQRES contain more residues than the usable ATOM Cα records?", "Compare contact counts with 6, 8 and 10 Å cutoffs while keeping sequence separation >2.",
    "SEQRES describes the expected deposited polymer sequence; some atoms are unresolved or have zero occupancy. Increasing a fixed distance cutoff cannot remove contacts. Proximity still does not establish affinity.",
    "Highlight the exported chain-B heme-neighbor residues in py3Dmol. Build selectors with chain, residue number and insertion code; use only the existing embedded PDB data.",
    "Add a residue-label table for the contact map so every observed index resolves to chain/resnum/icode. Keep missing residues absent from the distance matrix.",
    "Check first-model selection, insertion-code identity, deterministic alternate selection, symmetric distances, zero diagonal and unchanged original PDB text. Never treat experimental B-factors as pLDDT."),
  "zh-hans":("为什么 SEQRES 中的残基数可能多于有效 ATOM Cα 记录？", "在序列间隔 >2 的条件不变时，比较 6、8、10 Å 的接触数。",
    "SEQRES 描述沉积的预期聚合物序列，部分原子可能未解析或 occupancy 为零。对固定坐标增大距离阈值不会减少接触数，邻近关系仍不能证明亲和力。",
    "在 py3Dmol 中高亮导出的 B 链血红素邻近残基，使用链、残基编号及插入码构造选择器，仅使用已有内嵌 PDB。",
    "为接触图添加残基标签表，使每个观测索引对应 chain/resnum/icode，缺失残基仍不进入距离矩阵。",
    "检查第一个模型、插入码标识、确定性替代构象选择、距离对称及零对角线，并确认原始 PDB 不变；实验 B-factor 不当作 pLDDT。")},
}
